---
name: "Build Solution Architecture & Ops Manual"

on:
#  push:
#    tags:
#      - "v[0-9]+.[0-9]+.[0-9]+"
#      - "v*-rc[0-9]+"
  workflow_call:
    # inputs:
    #   version:
    #     required: true
    #     type: string
  workflow_dispatch:

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"

    steps:

      - uses: actions/checkout@v3
      - name: Set version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: "Run build of HTML version"
        run: ./dtcw generateHTML

      - name: zip html5 version
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r solution_architecture-${{ env.RELEASE_VERSION }}.zip build/html5
      
      - name: "Upload html5 version"
        uses: actions/upload-artifact@v4
        with:
          name: solution_architecture.zip
          path: solution_architecture-${{ env.RELEASE_VERSION }}.zip
          # retention-days: 90
          

      - name: "Remove help for PDF version"
        run: |
          find . -name "*\.adoc" -exec sed -i '/\*\*\*\*/,/\*\*\*\*/d' {} \;
          find . -name "*\.adoc" -exec sed -i '/arc42help/d' {} \;

      - name: "Run build of PDF version"
        run: ./dtcw generatePDF

      - name: "Rename solution_architecture.pdf with version"
        run: mv build/pdf/arc42/arc42.pdf solution_architecture-${{ env.RELEASE_VERSION }}.pdf

      - name: "Rename ops_manual.pdf with version"
        run: mv build/pdf/operations/ops_manual.pdf ops_manual-${{ env.RELEASE_VERSION }}.pdf

      - name: "Upload solution_architecture.pdf version"
        uses: actions/upload-artifact@v4
        with:
          name: solution_architecture.pdf
          path: solution_architecture-${{ env.RELEASE_VERSION }}.pdf

      - name: "Upload ops_manual.pdf version"
        uses: actions/upload-artifact@v4
        with:
          name: ops_manual.pdf
          path: ops_manual-${{ env.RELEASE_VERSION }}.pdf
          # retention-days: 90
