---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:

      - uses: actions/checkout@v3

      - name: "Run build of HTML version"
        run: ./dtcw generateHTML

      - name: "Upload html5 version"
        uses: actions/upload-artifact@v3.1.1
        with:
          name: html5
          path: build/html5
          retention-days: 90
          
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r html5.zip build/html5

      - name: "Run build of PDF version"
        run: ./dtcw generatePDF

      - name: "Upload PDF version"
        uses: actions/upload-artifact@v3.1.1
        with:
          name: PDF
          path: build/pdf/arc42/arc42.pdf
          retention-days: 90
          
      - name: "release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            html5.zip
            build/pdf/arc42/arc42.pdf