---
name: 'Deploy Docker Containers'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        #name: id_rsa # optional
        known_hosts: ${{ secrets.SSH_FINGERPRINT }}
        #config: ${{ secrets.CONFIG }} # ssh_config; optional
        #if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

    - name: Deploy Docker Containers
      run: |
        docker-compose ps -a
      env:
        DOCKER_HOST: ssh://<user>@<server-ip>
        #DOCKER_TLS_VERIFY: 1
        #DOCKER_CERT_PATH: /github/workspace/.ssh
