---
name: "build, release and deploy"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v*-rc[0-9]+"

jobs:
  build_arc_docs:
    uses: ./.github/workflows/build_arc_docs.yml
#    with:
#      config-path: .github/labeler.yml
#    secrets:
#      envPAT: ${{ secrets.envPAT }}
  release:
    uses: ./.github/workflows/release.yml
    # with:
    #   secrets:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}