---
name: 'build, release and deploy'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v*-rc[0-9]+'

jobs:
  build_docs:
    uses: ./.github/workflows/build_docs.yml
  release:
    uses: ./.github/workflows/release.yml
    needs: 'build_docs'

