---
name: "tagged-release"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:

      - uses: actions/checkout@v3
      - name: Set version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
              
      - name: "Download Arc42 html5 version"
        uses: actions/download-artifact@v4
        with:
          name: solution_architecture.zip

      - name: "Download Arc42 PDF version"
        uses: actions/download-artifact@v4
        with:
          name: solution_architecture.pdf

      - name: "Download Ops Manual PDF version"
        uses: actions/download-artifact@v4
        with:
          name: ops_manual.pdf
  
      - name: "release candidate"
        if: contains(github.event.ref, '-rc')
        uses: marvinpinto/action-automatic-releases@v2
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          # automatic_release_tag: "latest"
          files: |
            solution_architecture-${{ env.RELEASE_VERSION }}.zip
            solution_architecture-${{ env.RELEASE_VERSION }}.pdf
            ops_manual-${{ env.RELEASE_VERSION }}.pdf
        
      - name: "release"
        if: (!contains(github.event.ref, '-rc'))
        uses: marvinpinto/action-automatic-releases@v2
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            solution_architecture-${{ env.RELEASE_VERSION }}.zip
            solution_architecture-${{ env.RELEASE_VERSION }}.pdf
            ops_manual-${{ env.RELEASE_VERSION }}.pdf